---
name: Create a corporate repository

body:
  - type: markdown
    attributes:
      value: |
        ### Create a new corporate repository for Axa development team

  - type: dropdown
    attributes:
      label: "Repository visibility"
      description: The visibility of the newly created repository,
      options:
        - Public
        - Internal
        - Private
    validations:
      required: true

  - type: input
    attributes:
      label: ">>>repository-name<<<"
      description: The name of the repository to be created
      placeholder: repository name
    validations:
      required: true
