---
name: Create a corporate repository
title: "Create a corporate repository"
description: Create a corporate repository
labels:
assignees:

body:
  - type: markdown
    attributes:
      value: |
        ### Create a new corporate repository for Axa development team

  - type: dropdown
    attributes:
      label: "Repository visibility"
      description: The visibility of the newly created repository,
      options:
        - public
        - internal
        - private
    validations:
      required: true

  - type: input
    attributes:
      label: "Repository name"
      description: The name of the repository to be created
      placeholder: repository name
    validations:
      required: true
