---
name: Create GitHub Actions Required Workflows Enablement Repo
title: "Demo Creation :: enablement-gha-required-workflows-v1"
description: Create a Demo GitHub Actions Required Workflows Enablement repository
labels:
  - demo
  - template
  - tmpl:octodemo-resources/tmpl-gha-required-v1
assignees:
  - octodemobot


body:
  - type: markdown
    attributes:
      value: |
        ### Create an Enablement GitHub Actions Required Workflows Repository

        By opening an issue you will get an enablement repository to learn and experiment with GitHub Actions Required Workflows.
        
        _These demos are built out using the demo provisioning framework and will be subject to the demo lifecycle
        enforced by this repository, which will clean up "orphaned" demos that have been open for extended periods
        of time._

  - type: dropdown
    attributes:
      label: ">>>demo-repository-owner<<<"
      description: The organization to create the demo repository under,
      options:
        - octodemo-enablement
    validations:
      required: true

  - type: input
    attributes:
      label: ">>>demo-repository-name<<<"
      description: The name of the repository to be created, must be unique under the above owner/organization and compliant with repository naming conventions (i.e. no spaces).
      placeholder: repository name
    validations:
      required: true
