name: Protect repository

description: Set policies on repository

inputs:
  organization_name:
    description: The name of the organization
    required: true
  repository_name:
    description: The name of the repository
    required: true

outputs:
  error:
    description: The error message if the protection failed

runs:
  using: "node16"
  main: "dist/action.js"