name: Create Repository

description: Create a new repository

inputs:
  organization_name:
    description: The name of the organization
    required: true
  repository_name:
    description: The name of the repository
    required: true
  repository_visibility:
    description: The visibility of the repository
    required: false
    default: public
  maintainer:
    description: The username of the maintainer
    required: true

outputs:
  repository_id:
    description: The ID of the repository
  error:
    description: The error message if the creation failed

runs:
  using: "node16"
  main: "dist/action.js"