---
name: Create Repository
on:
  issues:
    types:
      - opened
      - reopened

jobs:

  extract_repository_settings:
    runs-on: ubuntu-latest
    outputs: 
      repository_name: ${{ steps.extract.outputs.repository_name }}
      repository_visibility: ${{ steps.extract.outputs.repository_visibility }}
    steps:
      - name: Extract repository settings
        id: extract
        run: |
          echo "${{ github.event.issue.body }}" >> body.txt
          echo "::set-output name=repository_name::$(awk '/### Repository name/{getline; getline; print}' body.txt)"
          echo "::set-output name=repository_visibility::$(awk '/### Repository visibility/{getline; getline; print}' body.txt)"

  display_repository_settings:
    runs-on: ubuntu-latest
    needs: extract_repository_settings
    steps:
      - name: Display repository settings
        run: |
          echo "Repository name: ${{ needs.extract_repository_settings.outputs.repository_name }}"
          echo "Repository visibility: ${{ needs.extract_repository_settings.outputs.repository_visibility }}"
