---
name: Create Repository
on:
  issues:
    types:
      - opened
      - reopened

jobs:

  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello World!"

  display_event: 
    runs-on: ubuntu-latest
    steps:
      - name: Display the event payload
        run: echo ${{ github.event.issue.id }}
        run: echo ${{ github.event.issue.title }}
        run: echo ${{ github.event.issue.body }}
